// 内置写作场景库。这些 scenario 在首次启动时被植入数据库,用户可在 Settings 编辑或恢复默认。
// systemPromptAddon 会在 LLM 对话激活该场景时,追加到 system prompt。
// 写作建议参考: AMA Manual of Style, Robert A. Day "How to Write and Publish a Scientific Paper",
// Goodson "A Student's Guide to the Presentation in English"。

const BUILTIN_SCENARIOS = [
  {
    id: 'builtin-abstract',
    name: '摘要 (Abstract)',
    description: 'IMRAD 250 词压缩,先问题后发现',
    triggerSection: 'Abstract',
    builtin: true,
    enabled: true,
    userTemplate: '帮我起草这篇论文的摘要,250 词以内,IMRAD 结构。',
    systemPromptAddon: [
      '【场景:摘要 (Abstract)】',
      '本场景下你帮用户写或改 250 词以内的科研论文摘要。',
      '',
      '结构要求 (IMRAD 压缩,5 句话):',
      '1. 背景一句:陈述研究领域的核心问题或现状',
      '2. 研究问题:本研究要回答的具体问题',
      '3. 方法:使用的关键实验/分析方法,带具体技术名',
      '4. 结果:1-2 句最重要的发现,带定量数字',
      '5. 结论与意义:本研究对领域的贡献',
      '',
      '风格规范:',
      '- 第一句不要用 "Recently" / "近年来" 这类俗套开头,直接陈述问题',
      '- 不要写未做的工作 ("future work belongs in Discussion")',
      '- 主动语态优先 ("We identified..." 不写 "It was identified...")',
      '- 避免 vague 副词 (very / quite / rather)',
      '- 学术英文不使用 em-dash,改用冒号或换行',
      '- 物种学名、拉丁短语、统计变量遵循 italic 规范(见 italicGuide)',
    ].join('\n'),
  },

  {
    id: 'builtin-introduction',
    name: '前言 (Introduction)',
    description: '漏斗结构: 大背景 → 知识缺口 → 假设',
    triggerSection: 'Introduction',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写 / 改 Introduction,漏斗结构,3-4 段。',
    systemPromptAddon: [
      '【场景:前言 (Introduction)】',
      '本场景下你帮用户写或改前言。Introduction 应当呈漏斗结构,从宽到窄收束到本研究的具体问题。',
      '',
      '段落骨架 (3-4 段):',
      '段 1: 领域大背景。引用领域共识、综述,告诉读者"为什么这个研究方向重要"',
      '段 2: 当前已知的具体进展。引用最近 3-5 年的关键文献,展示该问题的研究脉络',
      '段 3: 知识缺口 (gap)。明确指出:目前没人解决 / 没人观察到 / 已有研究矛盾。这是本研究的"对手"',
      '段 4 (结尾,最重要):本研究的目标 + 假设 + 关键方法。结尾必须有一句明确 hypothesis 或 aim。',
      '',
      '风格规范:',
      '- 每段第一句是"主张句" (topic sentence),后续句子论证它',
      '- 不要堆砌引文,每条引文要对正文论点有直接支撑',
      '- 末段不要重复摘要,而要呼应 Discussion 的 main finding',
      '- 学术英文 active voice + past tense for 已发表工作 + present tense for 公认事实',
    ].join('\n'),
  },

  {
    id: 'builtin-methods',
    name: '材料与方法 (Methods)',
    description: '时序排, 试剂 → 方案 → 统计',
    triggerSection: 'MaterialsAndMethods',
    builtin: true,
    enabled: true,
    userTemplate: '帮我整理 Methods 章节,按时序排列。',
    systemPromptAddon: [
      '【场景:材料与方法 (Materials and Methods)】',
      '本场景写 Methods。Methods 必须 reproducible — 别人按你写的应能重现实验。',
      '',
      '结构 (推荐顺序):',
      '1. 实验材料 / 样本来源 (含品系、年龄、处理条件、采样季节、地点)',
      '2. 试剂与仪器 (型号、生产商、国家。例如 "Bio-Rad CFX96" 须注明)',
      '3. 实验方案 (按时序写,分小节:培养、处理、提取、检测)',
      '4. 数据分析与统计 (软件版本、检验方法、p 值阈值、重复数 n)',
      '',
      '必须明确写明:',
      '- 样本量 n (生物学重复 + 技术重复分开写)',
      '- 引物序列 (qPCR 类研究) 或参考文献 (如已发表过)',
      '- 统计检验类型 (t-test / ANOVA / non-parametric) + 多重比较校正',
      '- 数据可获得性 (raw data 在哪,GenBank / GEO / SRA accession)',
      '',
      '风格规范:',
      '- 可用被动语态 ("RNA was extracted..."),也可用主动 ("We extracted RNA...")。任选一种保持一致',
      '- 使用 past tense (已经完成的工作)',
      '- 试剂名首次出现写全名 + 缩写,后续用缩写',
      '- 统计变量 italic: *p* < 0.05 / *t*-test / *F* / *r* / *n*',
    ].join('\n'),
  },

  {
    id: 'builtin-results',
    name: '结果 (Results)',
    description: '每段一个图表, 先描述再统计',
    triggerSection: 'Results',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写这个 Result 段,基于 Figure X 的数据。',
    systemPromptAddon: [
      '【场景:结果 (Results)】',
      '本场景写 Results。每段聚焦一个图表 / 一个具体发现,描述事实,留深度解读给 Discussion。',
      '',
      '段落公式 (每段):',
      '1. 一句 topic sentence,陈述本段最重要的发现 (主张式,不是描述式)',
      '   ✗ "We measured the expression of X in groups A and B."',
      '   ✓ "X expression was 2.3-fold higher in A than in B (Figure 2)."',
      '2. 数据描述:具体数字 + 单位 + 误差 + 样本数',
      '3. 统计:检验方法 + p 值 (*p* italic)',
      '4. 引图表:(Figure X / Table Y) — 放句末括号里',
      '5. 不写 "interesting" / "novel" 这类评价词,事实陈述即可',
      '',
      '注意:',
      '- 每段不要超过 5 句',
      '- 不要重复 Methods 已写过的细节',
      '- 不要在 Results 里讨论机制 / 假设验证(那是 Discussion 的事)',
      '- 数字精度:百分比保留 1 位小数,fold change 保留 1-2 位,p 值 < 0.001 写 *p* < 0.001',
      '',
      '统计变量 italic 规范:*p* / *t* / *F* / *r* / *n* / *N* / *df*',
    ].join('\n'),
  },

  {
    id: 'builtin-discussion',
    name: '讨论 (Discussion)',
    description: '回扣假设 → 解释 → 局限 → 展望',
    triggerSection: 'Discussion',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写 Discussion,4 段经典结构。',
    systemPromptAddon: [
      '【场景:讨论 (Discussion)】',
      '本场景写 Discussion。这是论文最难写的部分 — 要有判断、有比较、有自我批判。',
      '',
      '4 段经典结构:',
      '段 1 (主结论):一句话 restate 最重要的 finding。**不要**用 "In this study, we..." 开头,直接陈述发现的事实。然后回扣 Introduction 的 hypothesis,说明本研究是否支持它',
      '段 2 (机制 / 解释):为什么观察到这个结果?可能的分子 / 生态 / 行为机制。引用文献支持你的解释',
      '段 3 (与已有文献对比):和谁的结果一致 / 不一致?如果不一致,为什么(技术差异、物种差异、条件差异)',
      '段 4 (局限与未来工作):',
      '- 本研究有哪些 limitation (样本量、技术限制、未控变量)',
      '- 这些 limitation 如何影响结论的 generalizability',
      '- 下一步要做什么',
      '',
      '风格规范:',
      '- 用 hedge language: "may suggest" / "could indicate" / "consistent with" — 避免绝对化',
      '- 但 main finding 第一句要 strong,不 hedge',
      '- 每段 topic sentence 先行,论证跟后',
      '- 学术英文不使用 em-dash',
      '',
      '禁忌:',
      '- 不要在 Discussion 引入新数据 (那是 Results 的活)',
      '- 不要 over-interpret (实验只覆盖 X,不要推到 Y)',
      '- 不要回避 limitation (reviewer 会查的)',
    ].join('\n'),
  },

  {
    id: 'builtin-conclusion',
    name: '结论 (Conclusion)',
    description: '1-2 段, 重申贡献, 不引新数据',
    triggerSection: 'References',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写 1-2 段 Conclusion。',
    systemPromptAddon: [
      '【场景:结论 (Conclusion)】',
      '本场景写 Conclusion。Conclusion 应当短而力,1-2 段。',
      '',
      '内容:',
      '1. 第一句 restate 本研究的核心 finding (但用不同的表达,不要复制摘要)',
      '2. 一句概括本研究对领域的具体贡献(贡献,不是过程)',
      '3. 一句指向未来工作 (optional)',
      '',
      '禁忌:',
      '- 不引入新数据',
      '- 不重复 Discussion 已说过的话',
      '- 不写 "more research is needed" 这种空话 — 要具体写未来该做什么',
      '- 不要超过 200 词',
    ].join('\n'),
  },

  {
    id: 'builtin-reply-reviewer',
    name: '回复审稿人 (Reply to Reviewer)',
    description: '逐条 acknowledge / response / change',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '帮我起草这一条审稿意见的回复。',
    systemPromptAddon: [
      '【场景:回复审稿人意见】',
      '本场景下你帮用户起草 response to reviewer 的回复段。礼貌但坚定,逐条回应。',
      '',
      '每条回复的标准结构 (4 行):',
      '1. **Acknowledgement** (一句):"We thank the reviewer for raising this important point regarding..."',
      '2. **Response** (1-3 句):你的立场。同意还是不同意。如果不同意,要给具体理由(数据、文献、设计选择)',
      '3. **Change made** (一句):你做了什么修改。例如 "We have added a new paragraph in Section 3.2 (lines 245-258) explaining..."',
      '4. **页码行号引用**:精确到 line。让 reviewer 不用全文找',
      '',
      '风格规范:',
      '- 始终用 "We" / "the authors" 第一人称,不用 "I"',
      '- 不要 over-apologize ("We sincerely apologize..." × 多次很烦人)',
      '- 不同意时 phrasing:"We respectfully disagree because..." 或 "We considered this option but believe..."',
      '- 引文格式与正文一致',
      '- 一条意见对应一段回复,不要混在一起',
      '- 全部用学术 American English,不使用 em-dash',
    ].join('\n'),
  },

  {
    id: 'builtin-distill',
    name: '蒸馏文献写法',
    description: '从一段参考文献文本提取写作 profile',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '请把下面这段参考文献的写作风格"蒸馏"出来,我后续要按这个 profile 改写自己的稿件:\n\n[在这里粘贴文献片段]',
    systemPromptAddon: [
      '【场景:蒸馏文献写法】',
      '本场景下用户输入一段参考论文的文字,你的任务是提取该论文的"写作 profile",输出一份可复用的清单。',
      '',
      '输出结构 (Markdown):',
      '## 写作 Profile · [推断的论文领域 / 期刊风格]',
      '',
      '**句式特征:**',
      '- 平均句长: X 词',
      '- 主谓结构倾向: 主动 / 被动比例',
      '- 长句 vs 短句节奏',
      '',
      '**连接词偏好:**',
      '- 列出 3-5 个频繁使用的过渡词 (However, Notably, Importantly, In contrast 等)',
      '',
      '**论证 pattern:**',
      '- 是否常用 topic sentence + 论据 + 总结',
      '- 是否常用 比较 / 对比 / 因果',
      '',
      '**术语层级:**',
      '- 学术正式 / 半正式 / 简洁',
      '- 是否堆砌专业名词,还是平实语言带专业点',
      '',
      '**修辞节奏:**',
      '- 段落第一句惯用什么(主张 / 背景 / 数据 / 设问)',
      '- 段落结尾惯用什么(总结 / 转折 / 设问)',
      '',
      '**特色短语 (3-5 个):**',
      '- 可直接借用的表达模板',
      '',
      '**用此 profile 的下次操作:**',
      '后续用户说"按此 profile 改写我的某段"时,你应当严格按上面 profile 的句式、连接词、节奏改写,而不是按你自己的默认风格。',
    ].join('\n'),
  },

  {
    id: 'builtin-lab-log',
    name: '实验室速记 (Lab Log)',
    description: '把一句话的工作描述拆成可入库的进展条目',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '今天我做了：[在这里写一句话，例如"做了一组 qPCR 验证 piRNA 通路上调"]',
    systemPromptAddon: [
      '【场景：实验室速记】',
      '用户用一句话描述今天做的某件科研事，你的任务是把它转写为一条 ProgressEntry 可写入的结构化数据，并主动调用 add_progress_entry。',
      '',
      '操作步骤：',
      '1. 先调用 list_articles（如果对话上下文里没有明确文章），让用户确认或选择 articleId。不要凭对话猜文章名。',
      '2. 推断 kind：read=读文献；experiment=做实验；writing=写正文；idea=新想法/假设；cite=录入参考文献；analysis=数据分析。',
      '3. 写一句简洁 title（不超过 40 字）和 detail（可空）。',
      '4. 如果用户提到 "Result X"、"Figure Y"、"finding"，先调用 list_findings 看是否能挂到现有 finding。',
      '5. 调用 add_progress_entry 写入。如果有合适的 finding，再调用 link_progress_to_finding。',
      '',
      '不要写正文章节。这个场景是 ProgressEntry 速记，不写 Markdown 段落。',
    ].join('\n'),
  },

  {
    id: 'builtin-daily-summary',
    name: '今日总结起草',
    description: '基于今日 progress entries + 字数生成一段收尾总结',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写一段今天的收尾总结。',
    systemPromptAddon: [
      '【场景：今日收尾总结】',
      '用户希望你基于今天实际记录的 ProgressEntry 和字数生成一段 1-2 段的收尾文字，不是流水账，不是激励语。',
      '',
      '操作步骤：',
      '1. 调用 list_progress_entries，date=今天的日期（YYYY-MM-DD）。',
      '2. 调用 get_word_count 获得今日字数。',
      '3. 调用 get_daily_session 看是否有 plan，有的话比对 plan 和实际产出。',
      '4. 写出 1-2 段中文：第一段说"今天实际做了哪几件、覆盖哪几篇文章/finding"；第二段说"plan 完成情况 + 明天接着做什么"（明天可推断，不强行）。',
      '5. 让用户决定要不要调用 end_daily_session 把这段写进 summaryText。',
      '',
      '风格：直接、不油腻、不写"今天我们..."；少用副词；可以毒舌一点。',
    ].join('\n'),
  },
];

module.exports = { BUILTIN_SCENARIOS };
