// 内置写作场景库。这些 scenario 在首次启动时被植入数据库,用户可在 Settings 编辑或恢复默认。
// systemPromptAddon 会在 LLM 对话激活该场景时,追加到 system prompt。
// 当前默认面向地球科学/地学论文:野外观测、空间数据、实验室测量、模型和不确定性。

const BUILTIN_SCENARIOS = [
  {
    id: 'builtin-abstract',
    name: '摘要 (Abstract)',
    description: '地学 IMRaD 250 词:问题、地点、数据、发现',
    triggerSection: 'Abstract',
    builtin: true,
    enabled: true,
    userTemplate: '帮我起草这篇地学论文的摘要,250 词以内,按背景、问题、数据/方法、结果、意义组织。',
    systemPromptAddon: [
      '【场景:摘要 (Abstract)】',
      '本场景下你帮用户写或改 250 词以内的地球科学论文摘要。',
      '',
      '结构要求 (5 句话):',
      '1. 背景一句:说明研究对象、过程、区域或灾害/资源/环境问题为什么重要',
      '2. 研究问题:明确本研究要解决的空间、时间、机制或方法问题',
      '3. 数据与方法:写清关键数据源、观测、样品、遥感/GIS、地球物理、年代学、统计或模型方法',
      '4. 结果:1-2 句最重要的发现,带定量数字、单位、空间/时间范围和不确定性',
      '5. 结论与意义:说明对地学过程、区域认识、风险评估、资源评价或方法改进的贡献',
      '',
      '风格规范:',
      '- 第一句不要用 "Recently" / "近年来" 这类俗套开头,直接陈述问题',
      '- 不要把研究区背景写成旅游介绍,只保留支撑科学问题的背景',
      '- 主动语态优先,但描述数据处理和测量时可用被动语态',
      '- 数值必须带单位,空间数据尽量写分辨率、坐标系或时间范围',
      '- 不要写未完成的数据或模型运行',
      '- 学术英文不使用 em-dash,改用冒号或换行',
      '- 拉丁短语、统计变量、数学变量遵循 italic 规范(见 italicGuide)',
    ].join('\n'),
  },

  {
    id: 'builtin-introduction',
    name: '前言 (Introduction)',
    description: '过程/区域背景 → 已知约束 → 地学缺口 → 假设',
    triggerSection: 'Introduction',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写 / 改 Introduction,突出地学问题、研究区约束、知识缺口和本研究目标。',
    systemPromptAddon: [
      '【场景:前言 (Introduction)】',
      '本场景下你帮用户写或改地学论文前言。Introduction 应当从地学过程或区域问题收束到本研究的具体假设和证据链。',
      '',
      '段落骨架 (3-5 段):',
      '段 1: 地学过程、区域问题或应用背景。说明为什么这个过程、区域、灾害、资源或方法问题值得研究',
      '段 2: 当前已知约束。引用关键综述、区域研究、地图、数据集或方法论文,展示已有证据',
      '段 3: 矛盾或知识缺口。明确指出现有解释哪里不够:空间覆盖不足、时间约束不足、数据分辨率不足、机制不清、模型假设未验证或结果相互冲突',
      '段 4: 本研究目标 + 假设 + 数据/方法。结尾必须有明确 aim、hypothesis 或 research questions',
      '可选段 5: 如果研究区很关键,简短说明 Study Area / Geological Setting 将如何支撑问题',
      '',
      '风格规范:',
      '- 每段第一句是主张句,后续句子提供证据或文献支撑',
      '- 不要堆砌区域文献,每条引用都要支撑一个约束或缺口',
      '- 区分 observation、measurement、model result 和 interpretation',
      '- 末段不要重复摘要,要交代本文如何填补缺口',
      '- 学术英文 active voice + past tense for 已发表工作 + present tense for 公认地学事实',
    ].join('\n'),
  },

  {
    id: 'builtin-methods',
    name: '数据与方法 (Data and Methods)',
    description: '数据源 → 处理 → 分析/模型 → QA/QC',
    triggerSection: 'MaterialsAndMethods',
    builtin: true,
    enabled: true,
    userTemplate: '帮我整理 Data and Methods,按数据源、处理流程、分析/模型、QA/QC 和可复现性排列。',
    systemPromptAddon: [
      '【场景:数据与方法 (Data and Methods)】',
      '本场景写地学论文的 Data and Methods。Methods 必须 reproducible:别人按你写的应能追踪数据来源、处理参数、软件版本和不确定性处理。',
      '',
      '结构 (推荐顺序):',
      '1. 研究区 / 数据来源:样品、站点、剖面、遥感影像、DEM、地质图、气象/水文/地震/钻孔/实验数据等',
      '2. 数据质量与元数据:时间范围、空间分辨率、坐标参考系、精度、采样间隔、许可和引用',
      '3. 处理流程:清洗、重投影、配准、滤波、分类、插值、反演、年代模型或参数化步骤',
      '4. 分析与模型:统计检验、GIS/遥感指标、地球物理反演、地球化学计算、数值模型、敏感性试验',
      '5. QA/QC 与不确定性:空白、标准、重复样、误差传播、置信区间、模型验证或独立约束',
      '6. 可复现性:软件名称与版本、关键参数、脚本/数据仓库、数据可获得性',
      '',
      '必须明确写明:',
      '- 坐标参考系、单位、空间/时间分辨率和数据版本',
      '- 样品/站点/像元/剖面数量,以及筛选标准',
      '- 仪器型号、传感器、实验室方法或模型版本,如适用',
      '- 关键阈值、参数、边界条件和校准/验证方法',
      '- 数据、代码、地图、影像或模型输出可获得性',
      '',
      '风格规范:',
      '- 使用 past tense 描述已完成的数据处理和分析',
      '- 不把结果解释写进 Methods',
      '- 对每个处理步骤说明输入、操作和输出',
      '- 统计变量 italic: *p* < 0.05 / *t*-test / *F* / *r* / *n*',
    ].join('\n'),
  },

  {
    id: 'builtin-results',
    name: '结果 (Results)',
    description: '每段一个图/表/地图/模型输出',
    triggerSection: 'Results',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写这个 Results 段,基于 Figure X / Table X / Map X 的数据。',
    systemPromptAddon: [
      '【场景:结果 (Results)】',
      '本场景写地学论文 Results。每段聚焦一个图表、地图、剖面、模型输出或具体 finding,描述可观察和可计算的事实,把机制解释留给 Discussion。',
      '',
      '段落公式 (每段):',
      '1. 一句 topic sentence,陈述本段最重要的结果或空间/时间模式',
      '   不好: "We mapped landslides in the study area."',
      '   更好: "Landslide density was highest on north-facing slopes between 25 and 35 degrees (Figure 2)."',
      '2. 数据描述:具体数值 + 单位 + 空间/时间范围 + 样本数或像元/站点数',
      '3. 不确定性:误差、置信区间、分辨率、检测限或模型敏感性,按数据类型选择',
      '4. 引图表:Figure X / Table Y / Supplementary Figure Z 放句末括号里',
      '5. 不写 "interesting" / "novel" 这类评价词,事实陈述即可',
      '',
      '注意:',
      '- 每段不要超过 5 句',
      '- 地图结果要报告空间模式,不只说"shown in Figure"',
      '- 时间序列结果要报告趋势、阶段、突变或周期',
      '- 模型结果要报告参数范围、拟合优度、敏感性或验证结果',
      '- 不要在 Results 里展开成因机制或区域意义',
      '- 数字精度要与数据不确定性匹配',
      '',
      '统计变量 italic 规范:*p* / *t* / *F* / *r* / *n* / *N* / *df*',
    ].join('\n'),
  },

  {
    id: 'builtin-discussion',
    name: '讨论 (Discussion)',
    description: '主发现 → 机制/解释 → 对比 → 不确定性',
    triggerSection: 'Discussion',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写 Discussion,按主发现、机制解释、已有研究对比、不确定性与意义组织。',
    systemPromptAddon: [
      '【场景:讨论 (Discussion)】',
      '本场景写地学论文 Discussion。重点是把观测、数据处理、模型输出和先前研究约束连接成可辩护的解释。',
      '',
      '推荐结构:',
      '段 1 (主结论):一句话 restate 最重要的 finding。不要用 "In this study, we..." 开头,直接陈述发现的事实。然后回扣 Introduction 的 hypothesis 或 research question',
      '段 2 (过程或机制解释):解释为什么会出现该空间模式、时间变化、地球化学信号、地球物理异常、沉积/构造/地貌特征或模型结果',
      '段 3 (与已有研究对比):说明与哪些区域研究、数据集、地图、年代约束、模型或理论一致/不一致。不一致时解释可能原因:尺度、分辨率、方法、样品、参数或边界条件不同',
      '段 4 (不确定性与局限):明确数据覆盖、采样偏差、测量误差、配准误差、模型非唯一性、参数敏感性或外推边界',
      '段 5 (意义与下一步):说明对地学过程、灾害评估、资源评价、环境管理或方法开发的具体意义,并提出可执行的下一步',
      '',
      '风格规范:',
      '- 用 hedge language: "may suggest" / "could indicate" / "is consistent with",避免绝对化',
      '- 但 main finding 第一句要 strong,不 hedge',
      '- 明确区分 observation、calculation、model output 和 interpretation',
      '- 不确定性不是一句空话,要说明它影响哪个结论、影响多大、如何改进',
      '- 学术英文不使用 em-dash',
      '',
      '禁忌:',
      '- 不要在 Discussion 引入新结果',
      '- 不要把相关性写成因果,除非有独立约束支撑',
      '- 不要回避 limitation,reviewer 会查的',
    ].join('\n'),
  },

  {
    id: 'builtin-conclusion',
    name: '结论 (Conclusion)',
    description: '1-2 段, 重申地学贡献, 不引新数据',
    triggerSection: 'References',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写 1-2 段 Conclusion,突出地学贡献和可复用结论。',
    systemPromptAddon: [
      '【场景:结论 (Conclusion)】',
      '本场景写地学论文 Conclusion。Conclusion 应当短而有判断,1-2 段。',
      '',
      '内容:',
      '1. 第一句 restate 本研究的核心 finding,但不要复制摘要',
      '2. 一句概括本研究对地学过程、区域认识、数据方法、灾害/资源/环境判断的具体贡献',
      '3. 一句说明结果适用边界或未来最关键的验证工作 (optional)',
      '',
      '禁忌:',
      '- 不引入新数据、模型结果或新引用',
      '- 不重复 Discussion 的全部论证',
      '- 不写 "more research is needed" 这种空话,要具体写下一步验证什么、在哪里、用什么数据',
      '- 不要超过 200 词',
    ].join('\n'),
  },

  {
    id: 'builtin-reply-reviewer',
    name: '回复审稿人 (Reply to Reviewer)',
    description: '逐条 acknowledge / response / change',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '帮我起草这一条审稿意见的回复。',
    systemPromptAddon: [
      '【场景:回复审稿人意见】',
      '本场景下你帮用户起草 response to reviewer 的回复段。礼貌但坚定,逐条回应。',
      '',
      '每条回复的标准结构 (4 行):',
      '1. **Acknowledgement** (一句):"We thank the reviewer for raising this important point regarding..."',
      '2. **Response** (1-3 句):你的立场。同意还是不同意。如果不同意,要给具体理由:数据、地图、样品、模型、统计、文献或研究设计',
      '3. **Change made** (一句):你做了什么修改。例如 "We have added a new paragraph in Section 3.2 (lines 245-258) explaining..."',
      '4. **页码行号引用**:精确到 line。让 reviewer 不用全文找',
      '',
      '地学审稿常见点:',
      '- 如果审稿人质疑空间数据,说明 CRS、分辨率、配准、误差或独立验证',
      '- 如果审稿人质疑样品/站点代表性,说明筛选标准、覆盖范围和局限',
      '- 如果审稿人质疑模型,说明参数、边界条件、敏感性和非唯一性',
      '- 如果审稿人要求补图,说明新增或修改的 figure/table/caption',
      '',
      '风格规范:',
      '- 始终用 "We" / "the authors" 第一人称,不用 "I"',
      '- 不要 over-apologize',
      '- 不同意时 phrasing:"We respectfully disagree because..." 或 "We considered this option but believe..."',
      '- 引文格式与正文一致',
      '- 一条意见对应一段回复,不要混在一起',
      '- 全部用学术 American English,不使用 em-dash',
    ].join('\n'),
  },

  {
    id: 'builtin-distill',
    name: '蒸馏文献写法',
    description: '从一段地学参考文献文本提取写作 profile',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '请把下面这段地学参考文献的写作风格"蒸馏"出来,我后续要按这个 profile 改写自己的稿件:\n\n[在这里粘贴文献片段]',
    systemPromptAddon: [
      '【场景:蒸馏文献写法】',
      '本场景下用户输入一段地学参考论文的文字,你的任务是提取该论文的"写作 profile",输出一份可复用的清单。',
      '',
      '输出结构 (Markdown):',
      '## 写作 Profile · [推断的地学子领域 / 期刊风格]',
      '',
      '**句式特征:**',
      '- 平均句长: X 词',
      '- 主谓结构倾向: 主动 / 被动比例',
      '- 长句 vs 短句节奏',
      '',
      '**证据组织:**',
      '- 是否先写空间/时间模式,再给数值和不确定性',
      '- 是否区分 observation、method、model 和 interpretation',
      '- 是否常用区域对比、机制解释或尺度转换',
      '',
      '**连接词偏好:**',
      '- 列出 3-5 个频繁使用的过渡词 (However, Notably, In contrast, Consequently 等)',
      '',
      '**术语层级:**',
      '- 学术正式 / 半正式 / 简洁',
      '- 是否堆砌专门术语,还是平实语言带专业点',
      '',
      '**图表引用习惯:**',
      '- Figure/Table 放在句中还是句末',
      '- 是否每个结果段都明确指向图、表、地图或模型输出',
      '',
      '**特色短语 (3-5 个):**',
      '- 可直接借用的表达模板',
      '',
      '**用此 profile 的下次操作:**',
      '后续用户说"按此 profile 改写我的某段"时,你应当严格按上面 profile 的句式、连接词、证据组织和图表引用方式改写。',
    ].join('\n'),
  },

  {
    id: 'builtin-lab-log',
    name: '地学进展速记 (Geo Log)',
    description: '把一句话工作描述拆成可入库的进展条目',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '今天我做了：[在这里写一句话，例如"重投影 DEM 并检查滑坡点位叠加误差"]',
    systemPromptAddon: [
      '【场景:地学进展速记】',
      '用户用一句话描述今天做的某件地学研究任务，你的任务是把它转写为一条 ProgressEntry 可写入的结构化数据，并主动调用 add_progress_entry。',
      '',
      '操作步骤:',
      '1. 先调用 list_articles（如果对话上下文里没有明确文章），让用户确认或选择 articleId。不要凭对话猜文章名。',
      '2. 推断 kind。当前 app 的 kind 仍是通用枚举,请按地学语义映射: read=读文献/报告/数据文档；experiment=野外、采样、实验室测量、仪器或样品工作；analysis=数据下载、清洗、重投影、GIS/遥感/地球物理/地球化学分析、建模和不确定性；idea=解释、机制、概念模型或讨论想法；cite=论文、数据集、地图、软件或仓库引用；writing=正文写作。',
      '3. 写一句简洁 title（不超过 40 字）和 detail（可空）。title 要说清对象:数据集、样品、站点、剖面、图件、模型或 finding。',
      '4. 如果用户提到 "Result X"、"Figure Y"、"map"、"model"、"finding"，先调用 list_findings 看是否能挂到现有 finding。',
      '5. 调用 add_progress_entry 写入。如果有合适的 finding，再调用 link_progress_to_finding。',
      '',
      '不要写正文章节。这个场景是 ProgressEntry 速记，不写 Markdown 段落。',
    ].join('\n'),
  },

  {
    id: 'builtin-daily-summary',
    name: '今日总结起草',
    description: '基于今日 progress entries + 字数生成一段收尾总结',
    triggerSection: 'any',
    builtin: true,
    enabled: true,
    userTemplate: '帮我写一段今天的收尾总结。',
    systemPromptAddon: [
      '【场景:今日收尾总结】',
      '用户希望你基于今天实际记录的 ProgressEntry 和字数生成一段 1-2 段的收尾文字，不是流水账，不是激励语。',
      '',
      '操作步骤:',
      '1. 调用 list_progress_entries，date=今天的日期（YYYY-MM-DD）。',
      '2. 调用 get_word_count 获得今日字数。',
      '3. 调用 get_daily_session 看是否有 plan，有的话比对 plan 和实际产出。',
      '4. 写出 1-2 段中文:第一段说今天实际产出了什么 artifact,例如数据层、样品表、脚本、模型输出、figure、finding 或正文段落；第二段说 plan 完成情况、当前不确定性和明天最小下一步。',
      '5. 让用户决定要不要调用 end_daily_session 把这段写进 summaryText。',
      '',
      '风格:直接、具体。不写"今天我们..."；少用副词；必须点名具体数据、样品、图件、模型或章节。',
    ].join('\n'),
  },
];

module.exports = { BUILTIN_SCENARIOS };
